name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '🧰 Maintenance'
    label: 'refactor'
exclude-labels:
    - 'translations'
change-template: '- $TITLE (#$NUMBER)'
template: |
  ## Changes

  $CHANGES