name: Update Schema

on:
#  schedule:
#    - cron: "0 0 * * mon"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download and update the schema
        run: |
          git config user.name 'Choco Machine User'
          git config user.email 'machine@choco.com'
          
          schema_file="data/src/main/graphql/schema.json"
          json="$(curl -X GET https://choco-doc.s3-eu-west-1.amazonaws.com/choco-appsync/gql_schema/schema.json | json_pp)"

          echo $json | jq -r .data > $schema_file
          
          git add $schema_file
          git commit -m "Update schema"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ secrets.CHOCO_MACHINE_USER }}
          branch: _master/update-schema
          delete-branch: true
          title: 'Update Schema'
          body: 'Update Schema with last @chocoapp/choco-appsync master version'
