name: Test Coverage

on:
  push:
    branches:
      - feature/upload-code-quality-percentage

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@feature/upload-code-quality-percentage
      - name: Notify Codeclimate Coverage
        run: |
          chmod +x scripts/notify_code_climate.sh
          ./scripts/notify_code_climate.sh

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        run: bash ./gradlew testQaUnitTestCoverage

      - name: Upload Codeclimate Coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          chmod +x scripts/upload_coverage.sh
          ./scripts/upload_coverage.sh
