name: Test Coverage

on:
  push:
    branches:
      - feature/upload-code-quality-percentage

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Notify Codeclimate Coverage
        run: |
          chmod +x scripts/notify_code_climate.sh
          ./scripts/notify_code_climate.sh

      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Unit tests
        run: bash ./gradlew testQaUnitTest

      - name: Upload Codeclimate Coverage
        env:
          CC_TEST_REPORTER_ID: 3b545cb2bd8e831b401989bb763447278bb2218a734b34304142f87fae2d4e78
        run: |
          chmod +x scripts/upload_coverage.sh
          ./scripts/upload_coverage.sh
